#pragma once

// Canonical metadata compiled into HELLO_ACK and read by the artifact builder.
#define PHYSALIX_FIRMWARE_VERSION_MAJOR 1
#define PHYSALIX_FIRMWARE_VERSION_MINOR 0
#define PHYSALIX_FIRMWARE_VERSION_PATCH 0

#define PHYSALIX_PROTOCOL_VERSION 1

#define PHYSALIX_CAPABILITY_ANALOG_A0 0x00000001UL
#define PHYSALIX_CAPABILITY_DIGITAL_STEP 0x00000002UL
#define PHYSALIX_CAPABILITY_TIMER1_ADC_IRQ 0x00000004UL
#define PHYSALIX_REQUIRED_CAPABILITIES 0x00000007UL
